In [27]:
import numpy as np

In [28]:
a = [10,11,12,13,14,15]

In [29]:
n_a = np.array(a)

In [30]:
a[-2]

14

In [31]:
n_a[0:3]

array([10, 11, 12])

In [32]:
np.sum(n_a)

75

In [33]:
np.max(n_a)

15

In [34]:
np.min(n_a)

10

In [35]:
np.average(n_a)

12.5

In [36]:
n_random = np.random.random(10)

In [37]:
n_random

array([0.47055289, 0.31431877, 0.10094719, 0.15379654, 0.96107102,
       0.43903828, 0.36406763, 0.69793981, 0.33357698, 0.5299528 ])

In [38]:
np.max(n_random)


0.9610710197673311

In [39]:
np.min(n_random)

0.10094718690527771

In [40]:
np.sort(n_random)

array([0.10094719, 0.15379654, 0.31431877, 0.33357698, 0.36406763,
       0.43903828, 0.47055289, 0.5299528 , 0.69793981, 0.96107102])

In [41]:
np.argsort(n_random)

array([2, 3, 1, 8, 6, 5, 0, 9, 7, 4])